<a href="https://colab.research.google.com/github/riad234/IPB-Semester2-PengenalanPola/blob/Minggu1/PP_Riad_Minggu1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Vektor

In [ ]:
# vektor python numpy with range value
import numpy as np
print("vektor default python\n")
a = np.arange(1,20,1)
b = np.arange(1,20,2)

import numpy as np
print (" \n vektor via numpy \n")
# vektor via numpy
c = np.array ([1,2,3,4,5])
d = np.array ([1.5, 2.5, 5, 6, 7])

print(a)
print(b)
print(a.ndim)
print(a.shape)

vektor default python

 
 vektor via numpy 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
1
(19,)


# 2. Matrix

In [ ]:
# mengubah dari 1D menjadi matrik 2D
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# 3. List

In [ ]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]
print(list1);

# a. Menggabungkan list
gabung = list1 + list2 + list3 + list4
print("\na. Menggabungkan List")
print(gabung)

# b. Mengambil nilai
print("\nb. Mengambil nilai dari List")
print(list1[0])   # elemen pertama
print(list1[1])   # elemen kedua
print(list1[-1])  # elemen terakhir

# c. Menyisipkan nilai ke list
list2.insert(4, 11)
print("\nc. Menyisipkan nilai ke list2 (elemen 4 - 11)")
print(list2)

# d. Menghapus nilai dari list
print("\nd. Menghapus nilai dari list")
## Cara 1: remove() (berdasarkan nilai)
list1.remove("banana")
print(list1)
## Cara 2: pop() (berdasarkan index)
list1.pop(0)
print(list1)
## Cara 3: del
del list4[1]
print(list4)

# e. Mengurutkan isi list
# List harus berisi tipe data yang sama (semua angka atau semua string).
print("\ne. Mengurutkan isi list")
## Mengurutkan list angka
print("mengurutkan list angka")
list2.sort()
print(list2)
## Mengurutkan list string
print("mengurutkan list string")
list1.sort()
print(list1)
## Urutan terbalik
print("mengurutkan list secara terbalik")
list2.sort(reverse=True)
print(list2)

['apple', 'banana', 'cherry']

a. Menggabungkan List
['apple', 'banana', 'cherry', 1, 5, 7, 9, 3, True, False, False, 'abc', 34, True, 40, 'male']

b. Mengambil nilai dari List
apple
banana
cherry

c. Menyisipkan nilai ke list2 (elemen 4 - 11)
[1, 5, 7, 9, 11, 3]

d. Menghapus nilai dari list
['apple', 'cherry']
['cherry']
['abc', True, 40, 'male']

e. Mengurutkan isi list
mengurutkan list angka
[1, 3, 5, 7, 9, 11]
mengurutkan list string
['cherry']
mengurutkan list secara terbalik
[11, 9, 7, 5, 3, 1]


# 4. Data Frame

In [ ]:
#data frame
import pandas as pd
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
 columns=['a', 'b', 'c'])
print(df)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9
